### ISSUE TITLE
Typo in NginxProxy/conf.d/default.conf

### ISSUE THREAD

**Issue by guillaumevds** [inensus/MPManager#2]
Hello,

In file NginxProxy/conf.d/default.conf :

Line 29 contains the character '*' which prevents Nginx from starting.

Best regards,

**Comment by alchalade** [comment]
Hello guillaumevds,
actually `default.conf` is generated file, therefore the file should never be in git.
Thank you for letting us know about that problem

It removed with other files that should not be here.

Tipp: You can either delete the file and build the containers again (actually Nginx would be enough)
