### ISSUE TITLE
Setup fails, unable to seed database

### ISSUE THREAD

**Issue by espenairmine** [inensus/MPManager#284]
When following the instructions, step 2 fails:

![image](https://user-images.githubusercontent.com/51234981/226103671-ab7c4b47-35d4-45a4-bdb9-41732b68237e.png)

Windows 11, Docker Desktop 4.17.0 (99724)

**Comment by dmohns** [comment]
This seems to be related to the release of PHP 8.1 on **November 25, 2021**. Looking at the history of commits and the CI pipeline, the last confirmed working commit (i.e. were the CI was passing) was from `November 5, 2021`, i.e. running PHP 8.0

As the PHP (minor) version is not pinned anywhere in the docker-compose files, running the the docker compose today will automatically run `PHP 8.2.4`. However, the PHP dependencies are pinned to version incompatible with PHP 8.1 via `composer.lock`. I'm sure there is multiple dependencies affected, this is an example: https://github.com/symfony/symfony/pull/42260

I see two solutions here:

- (preferred) Update all PHP dependencies to the latest version which is compatible with `PHP<9`.
- Pin PHP version to 8.0 in the compose files

As for option 1, I can conform after running 

```
php composer.phar update
```

inside the container, things seem to work.

**Comment by alchalade** [comment]
Actually, that happened because the docker files were set to  `php:8-apache` (implicitly on 8.0 back then) images 😞 . The fix, for now, is using `PHP:8-0-apache` images.
