### ISSUE TITLE
Issues of deprecated dependencies.

### ISSUE THREAD

**Issue by Delyc** [inensus/MPManager#287]
When trying to access http://mpmanager.local/, I run into the issues of **deprecated**, as shown in the image below

![image](https://user-images.githubusercontent.com/90575886/234534419-8ba3fb5c-2800-4b3b-8a6c-d655da838f57.png)

**Comment by 93Kamuran** [comment]
I can not reproduce that.

Please pull the latest master and run the app with "docker-compose up --build".
