### ISSUE TITLE
Documentation wrong: Building the frontend

### ISSUE THREAD

**Issue by dmohns** [inensus/MPManager#292]
The documentation section explain how to build the frontend seems incorrect https://github.com/inensus/MPManager/blob/master/README.md#building-the-frontend

> The project will automatically build the frontend in **production** mode. If you want to build the project in **development** mode, change the `NMP_MODE` variable in the `.env` file.

This is not what happens 🙃

1. The environment variable that determines the NPM mode is called `APP_ENV`, see https://github.com/inensus/MPManager/blob/master/Docker/configuration/npm/start.sh#L11
2. The default mode is `development` not `production`, see https://github.com/inensus/MPManager/blob/master/Website/htdocs/mpmanager/.env#L2

**Comment by alchalade** [comment]
Nice catch, do you want to raise a PR to fix this? 🙂

**Comment by dmohns** [comment]
Sure, sent 😉 

Question is, if I also need to update references here:

- https://github.com/inensus/MPManager/blob/master/docs/source/installation/frontend.rst#L6
- https://github.com/inensus/MPManager/blob/master/docs/source/_build/html/fr/_sources/installation/frontend.rst.txt#L6

but I guess no?
