### ISSUE TITLE
Lacking attribute in database

### ISSUE THREAD

**Issue by guillaumevds** [inensus/MPManager#3]
Hello,

When trying to open a meter in the web interface I get the following error :   
Column not found: 1054 Unknown column 'people.deleted_at' in 'where clause' (SQL: select * from `people` where `people`.`id` in (1) and `people`.`deleted_at` is null)

Which I fixed with :  
ALTER TABLE `people` ADD `deleted_at` DATETIME NULL AFTER `updated_at`;

**Comment by alchalade** [comment]
This should be solved. I've added the missing column into the database migration.
